"""
Dynamic App Idea Generator for Ideation Bot (@ideated_bot).
Every field (app name, overview, user stories, personas) is generated by the
Anthropic Claude API -- nothing here is templated or fabricated locally.

Model: Claude Haiku 4.5 -- the cheapest current Claude model, which is plenty
for short, structured idea-generation output. Structured outputs
(output_config.format) constrain the response to the required JSON shape, so
there's no free-text parsing to get wrong.

Generated ideas are cached in SQLite (database.py), keyed by article URL, so
that: (1) the same article never re-spends an API call twice, and (2) if a
live Claude call fails for an article that was already generated before, we
can still serve that previously LLM-generated idea instead of inventing one.
If neither a cache hit nor a live Claude call succeeds, the article is
skipped rather than backfilled with fake content.

Every live call also goes through rate_limiter.allow_call() first, so a burst
of Telegram taps can't blow through the API budget (see rate_limiter.py).
"""

import os
import json
import logging

import anthropic

import database
import rate_limiter

logger = logging.getLogger(__name__)

database.init_db()

# Required keys we expect back from Claude.
_REQUIRED_KEYS = ["app_name", "overview", "smooth_path", "hard_path", "potential_users"]

# Cheapest current Claude model -- $1/$5 per MTok. No thinking/effort needed
# for this task, so those params are omitted entirely (Haiku 4.5 doesn't
# support adaptive thinking or the effort parameter anyway).
_CLAUDE_MODEL = "claude-haiku-4-5"

# JSON schema passed as output_config.format so Claude's structured-output
# mode enforces shape, rather than relying on prompt wording + free-text parsing.
_RESPONSE_SCHEMA = {
    "type": "object",
    "properties": {
        "app_name": {"type": "string"},
        "overview": {"type": "string"},
        "smooth_path": {"type": "string"},
        "hard_path": {"type": "string"},
        "potential_users": {
            "type": "array",
            "items": {"type": "string"},
        },
    },
    "required": _REQUIRED_KEYS,
    "additionalProperties": False,
}


def call_claude_api(prompt: str, api_key: str) -> tuple[dict, str] | None:
    """
    Calls Claude Haiku 4.5 with a JSON-schema-constrained response.
    Returns (parsed_dict, model_name) on success, or None if the call is
    skipped (rate budget exhausted), refused, fails auth, or the response
    doesn't parse into the required shape.
    """
    if not rate_limiter.allow_call():
        return None

    client = anthropic.Anthropic(api_key=api_key)
    try:
        response = client.messages.create(
            model=_CLAUDE_MODEL,
            max_tokens=1024,
            output_config={"format": {"type": "json_schema", "schema": _RESPONSE_SCHEMA}},
            messages=[{"role": "user", "content": prompt}],
        )
    except anthropic.AuthenticationError:
        logger.warning("Claude API auth failure -- check ANTHROPIC_API_KEY.")
        return None
    except anthropic.RateLimitError as e:
        logger.warning(f"Claude API rate-limited: {e}")
        return None
    except anthropic.APIStatusError as e:
        logger.warning(f"Claude API error ({e.status_code}): {e.message}")
        return None
    except anthropic.APIConnectionError as e:
        logger.warning(f"Claude API connection error: {e}")
        return None

    if response.stop_reason == "refusal":
        logger.warning("Claude declined the request (stop_reason=refusal).")
        return None

    text = next((b.text for b in response.content if b.type == "text"), None)
    if not text:
        logger.warning(f"Claude API returned no text content (stop_reason={response.stop_reason}).")
        return None

    try:
        parsed = json.loads(text)
    except json.JSONDecodeError as e:
        logger.warning(f"Claude API JSON parse failed: {e} | raw={text[:300]}")
        return None

    if not isinstance(parsed, dict) or not all(k in parsed for k in _REQUIRED_KEYS):
        logger.warning(f"Claude API JSON missing required keys: {parsed}")
        return None

    return parsed, _CLAUDE_MODEL


def _assemble_idea(llm_result: dict, citation_html: str) -> dict:
    return {
        "title": llm_result.get("app_name", "Untitled App Idea"),
        "overview": llm_result.get("overview", ""),
        "smooth_path": llm_result.get("smooth_path", ""),
        "hard_path": llm_result.get("hard_path", ""),
        "potential_users": llm_result.get("potential_users", []),
        "citation_html": citation_html,
    }


def generate_app_idea(article: dict, index: int) -> dict | None:
    """
    Generates an app idea for a scraped Straits Times article, entirely from Claude.

    Order of operations:
    1. Return a cached idea if this exact article URL was generated before.
    2. Otherwise call Claude live (subject to rate_limiter's budget) and cache the result.
    3. If neither works (no key, rate-limited, or the call fails), return None so the
       caller can skip this article -- we never fabricate a placeholder idea.
    """
    headline = article.get("headline", "")
    summary = article.get("summary", "")
    theme_name = article.get("theme_name", "Singapore News")
    theme_key = article.get("theme_key", "")
    url = article.get("url", "https://www.straitstimes.com")
    date = article.get("date", "Recent News")

    citation_html = f"• <a href=\"{url}\">The Straits Times: {headline} ({date})</a>"

    cached = database.get_cached_idea(url)
    if cached:
        logger.info(f"Article {index}: reusing DB-cached Claude idea (model={cached['model_used']}).")
        return _assemble_idea(cached, citation_html)

    claude_key = os.getenv("ANTHROPIC_API_KEY")
    if not claude_key or claude_key == "your_anthropic_api_key_here":
        logger.warning(f"Article {index}: ANTHROPIC_API_KEY missing/placeholder, skipping '{headline}'.")
        return None

    prompt = (
        f"You are an expert product manager in Singapore creating a novel mobile/web app idea based on a specific Straits Times news article.\n\n"
        f"NEWS ARTICLE:\n"
        f"- Theme: {theme_name}\n"
        f"- Headline: \"{headline}\"\n"
        f"- Article Context: \"{summary}\"\n\n"
        f"Generate a novel application idea grounded in this news article. Be specific to the facts, "
        f"people, places, or organizations mentioned in the headline and article context above -- do not "
        f"produce a generic idea that could apply to any Singapore news story.\n\n"
        f"Fill in the following 5 fields:\n"
        f"1. \"app_name\": A creative app title (e.g. \"AquaBreeder — Seabass Hatchery Telemetry\").\n"
        f"2. \"overview\": A 2-3 sentence big picture overview explaining what the app does and how it addresses the news story in SG.\n"
        f"3. \"smooth_path\": A smooth path user story in the EXACT format: \"As a [type of user], I want [an action] so that [a benefit/value].\"\n"
        f"4. \"hard_path\": A hard path user story (handling edge cases, friction) in the EXACT format: \"As a [type of user], I want [an action] so that [a benefit/value].\"\n"
        f"5. \"potential_users\": A JSON list of 3 to 4 specific Singaporean target user personas.\n"
    )

    result = call_claude_api(prompt, claude_key)
    if not result:
        logger.warning(f"Article {index}: Claude call failed or was rate-limited, skipping '{headline}'.")
        return None

    llm_result, model_used = result
    database.save_idea(url, theme_key, headline, llm_result, model_used)
    logger.info(f"Article {index}: Claude-generated idea used (model={model_used}, '{llm_result.get('app_name', '')[:40]}...')")

    return _assemble_idea(llm_result, citation_html)


# Telegram hard-caps a single message at 4096 characters.
_TELEGRAM_MSG_LIMIT = 4096


def _split_for_telegram(text: str, limit: int = _TELEGRAM_MSG_LIMIT) -> list:
    """
    Defensive safety net: splits text on paragraph/line boundaries so no single
    message exceeds Telegram's limit, in case one idea's LLM output ever runs long.
    """
    if len(text) <= limit:
        return [text]

    parts = []
    while len(text) > limit:
        cut = text.rfind("\n\n", 0, limit)
        if cut == -1:
            cut = text.rfind("\n", 0, limit)
        if cut == -1:
            cut = limit
        parts.append(text[:cut])
        text = text[cut:].lstrip("\n")
    if text:
        parts.append(text)
    return parts


def format_live_ideas_chunks(theme_key: str, articles: list) -> list:
    """
    Formats scraped live Straits Times articles into a list of Telegram HTML messages:
    one short header message, followed by one message per idea (each well under
    Telegram's 4096-char limit, since bundling multiple LLM-written ideas per
    message previously overflowed it). Articles for which Claude could not
    produce an idea (live or cached) are skipped.
    """
    if not articles:
        return ["<b>No recent Straits Times news articles found for this theme in the last year.</b>"]

    theme_name = articles[0]["theme_name"] if articles else "Singapore News"

    ideas = [idea for idea in (generate_app_idea(art, i) for i, art in enumerate(articles, start=1)) if idea]

    if not ideas:
        return [
            "<b>Claude couldn't generate any app ideas right now.</b>\n\n"
            "This can happen if the API key is missing/invalid, the request budget was hit, "
            "or the daily rate limit was reached. Please try again shortly."
        ]

    def _format_single(idx, idea):
        users_str = "\n".join(f"• {u}" for u in idea["potential_users"]) if isinstance(idea["potential_users"], list) else str(idea["potential_users"])
        return (
            f"<b>{idx}. {idea['title']}</b>\n"
            f"📌 <b>Big Picture Overview:</b>\n{idea['overview']}\n\n"
            f"🧭 <b>User Journeys To Consider:</b>\n"
            f"• \"{idea['smooth_path']}\"\n"
            f"• \"{idea['hard_path']}\"\n\n"
            f"👥 <b>Potential Users:</b>\n{users_str}\n\n"
            f"📰 <b>Evidence & News Citation:</b>\n{idea['citation_html']}"
        )

    messages = []
    for i, idea in enumerate(ideas, start=1):
        messages.extend(_split_for_telegram(_format_single(i, idea)))

    return messages
